- hosts: ec2
  become: true
  vars:
    vulnwhisperer:
      prefix: "/opt"
      location: "vulnwhisperer"
      venv_location: "vulnwhisperer_venv"
      repository: "https://github.com/HASecuritySolutions/VulnWhisperer.git"
      configuration_file_name: "vulnwhisperer.ini"
  vars_prompt:
    - name: install_option
      prompt: "Please input either install or update"
      private: no
    - name: configuration_file
      prompt: "Full path to the VulnWhisperer configuration file"
      private: no
    - name: es_api_basic_auth_username
      prompt: "Username for elasticsearch authentication"
    - name: es_api_basic_auth_password
      prompt: "Password for elasticsearch authentication"
  pre_tasks:
    - name: assert the correct input is provided
      fail:
        msg: "Please specify one of either 'install' or 'update'"
      when: install_option != "install" and install_option != "update"
    - name: check that the provided configuration file exists
      become: false
      local_action: stat path="{{ configuration_file }}"
      ignore_errors: true
      register: configuration_file_stat
    - name: fail if the file is not available
      fail:
        msg: "Configuration file {{ configuration_file }} not found or inaccessible"
      when: not configuration_file_stat.stat.exists
  roles:
    - role: elastic.elasticsearch
      # set to true to enable closed source version
      es_enable_xpack: false
      es_instance_name: "vulnwhisperer"
      es_major_version: "6.x"
      es_version: "6.5.0"
      update_java: true
    - role: geerlingguy.kibana
      kibana_version: "6.x"
      kibana_package: kibana-oss
      kibana_package_state: present
      kibana_service_state: started
      kibana_service_enabled: true
      kibana_elasticsearch_url: "http://localhost:9200"
      kibana_elasticsearch_username: "{{ es_api_basic_auth_username }}"
      kibana_elasticsearch_password: "{{ es_api_basic_auth_password }}"
    - role: vulnwhisperer
      tags: "{{ install_option }}"
